project:
  type: website

website:
  title: "ISSS608VAA"
  navbar:
    left:
    
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 2" 
        
     
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

